name: build
on:
  pull_request:
    branches:
      - master
  workflow_dispatch:
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: '0'

    - name: Setup Node.js
      uses: actions/setup-node@v5
      with:
        node-version: '22'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Run test coverage
      run: npm run test:coverage

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      if: always()
      with:
        file: ./coverage/lcov.info
        flags: webapp
        name: webapp-coverage
        fail_ci_if_error: false

  build:
    runs-on: ubuntu-latest
    needs: test  # Only build if tests pass

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: '0'

    - name: Checkout docker-netbootxyz for container source files
      uses: actions/checkout@v4
      with:
        repository: netbootxyz/docker-netbootxyz
        path: docker-netbootxyz

    - name: Build the Docker image
      run: docker build .
