#!/usr/bin/with-contenv bash

# create local logs dir
mkdir -p \
  /config/menus/remote \
  /config/menus/local

# just download/extract static dev file for now
# future logic will download a build basedo n env variable and keep up to date overlaying users custom stuff
if [[ ! -f /menus/remote/menu.ipxe ]]; then
  curl -o \
    /tmp/menus.tar.gz -L \
	  "https://netboot-test.s3-us-west-2.amazonaws.com/menus.tar.gz"
  tar xf \
    /tmp/menus.tar.gz -C \
    /config/menus/remote
  cp /config/menus/remote/* /menus
fi
# Ownership
chown -R abc:abc /config
